version: '3'

volumes:
  datafiles:

services:
  database:
    image: mysql:latest
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw

  backend:
    image: bimelimski/backendgrp7
    build:
      context: . 
      dockerfile:       
    depends_on:
      - database
    ports:
      - "8081:80"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    image: bimelimski/frontendgrp7
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - backend
    ports: 
      - "8080:80"
    restart: always
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development

# run this in powershell from root-folder      
  #docker-compose -f docker-compose.yml up
# 